### ISSUE TITLE
CakePHP - plugins directory change

### ISSUE THREAD

**Issue by Perzonallica** [elboletaire/less-cake-plugin#1]
Hello, it's me again. :)

The CakePHP guys changed the plugin's directory in their latest commit. Now every plugin is saved into the vendor folder. So your plugin is working without problems, but only if I copy the LessHelper.php into \View\Helper directory.

If you will have some time, maybe you can look into it. :) Thanks!

**Comment by elboletaire** [comment]
Could you, please, paste here the link to that commit?

Thanks :)

**Comment by elboletaire** [comment]
Ok, I've found it

https://github.com/cakephp/cakephp/commit/7e091384e660f3e30e32767675ca46c518604778

**Comment by elboletaire** [comment]
I think we should wait for the plugin-installer to be updated. In the previous pasted commit I can read:

> Doing this frees up /plugins for in-app plugins. The core plugin-installer will be updated shortly.

The plugin-installer should do the clone / move stuff automatically when the composer package type is set to "cakephp-plugin".

I think this will be fixed when they update the `plugin-installer`.

**Comment by elboletaire** [comment]
After testing it I can see that plugins are now installed onto vendor directory but they're also appended to a cakephp file inside vendor folder named `cakephp-plugins.php` which is a mapping of the cakephp plugins located under the vendor folder.

Works as expected. BTW, thanks for your feedback :smile:

**Comment by Perzonallica** [comment]
Cool, thanks! :)

And in the future, maybe you should add this line to the Readme.md file, because without this line in AppController.php (or somewhere else), the plugin won't work:

```
public $helpers = ['Less.Less'];
```

**Comment by elboletaire** [comment]
Oh, thanks!

As this is a split from the twbs-cake-plugin I forgot to add some of this plugin information :sweat_smile: .
