### ISSUE TITLE
Path to "less" files

### ISSUE THREAD

**Issue by Zat42** [elboletaire/less-cake-plugin#10]
Hi,

I have a little problem that I can't solve, when I try to pull my compiled less files in the css block, I got an error.

Here are the folders where are my files :

<code>--webroot /</code>
<code>----css /</code>
<code>------style.css</code>
<code>------other.css</code>
<code>------less /</code>
<code>--------main.less</code>
<code> ----js/</code>
<code> ----img/</code>

Here is the code I use :

<code>echo $this->Html->css('less/main.less?', ['block' => true, 'rel' => 'stylesheet/less']);</code>
<code>echo $this->Less->fetch(); // it seems the problem comes from here</code>
<code>echo $this->fetch('css');</code>

And the error :

<code>
FileError: 'http://localhost/my_project/my_project/css/less/main.less' wasn't found (404)
</code>

The correct path is, obviously, this one :

<code>
http://localhost/my_project/css/less/main.less
</code>

For a reason that I can't find, "my_project" is duplicated in the path.

**Comment by elboletaire** [comment]
I'll add some tests to check this specific behaviour, but you can easily fix it changing your less folder to be inside webroot, like the css, img, and js folders:

```
--webroot /
----css /
------style.css
------other.css
----js/
----img/
----less /
------main.less
```

After that it should work.

**Comment by Zat42** [comment]
Saddly, it doesn't work but I have found a little trick to do this without getting an error : (less folder have to be in webroot folder, not css folder)

<code>$this->Html->css($this->Less->compile(array('less/main.less')), ['block' => 'css']);</code>

**Comment by elboletaire** [comment]
Oh, wait... I (wrongly) understood that you were using the `fetch` or the `less` methods...

You shall use one of those methods... the `compile` method is used internally by them (it needs the options to be set in the proper way). 

Use one of those methods and that's it.

I need to do something with that to avoid confusions... maybe make it private, as probably nobody will use it.

Again, thanks for the report. This things help me make the plugin better :)
