### ISSUE TITLE
fullBase Url

### ISSUE THREAD

**Issue by dspaeth-faber** [elboletaire/less-cake-plugin#8]
Hi,

I try to generate a css URL with full base.
How can I get this to work?

```
$this->Less->less('less/pdf.less', ['fullBase' => true]);
```

does not work.

thanks & regards 
Dieter

**Comment by elboletaire** [comment]
Why do you want it with full base? The plugin works with relative paths.

**Comment by dspaeth-faber** [comment]
I use this plugin in conjunction with CakePdf. CakePdf needs full urls.

**Comment by elboletaire** [comment]
It does not negatively affect the plugin, so let's add it.

Merge Requests are welcome
